version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./my_dbdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=units
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
volumes:
  my_dbdata: